export const slides = [
  {
    imageSrc: '/image/Rectangle_6.png',
  },
  {
    imageSrc: '/image/Rectangle_6.png',
  },
  {
    imageSrc: '/image/Rectangle_6.png',
  }
];

export const description = `
PersonalityTalk adalah lembaga yang bergerak di bidang jasa training, coaching, dan consulting dalam bidang psikologi. Berdiri sejak tahun 2014, Alhamdulillah PersonalityTalk telah membantu banyak orang dalam menyelesaikan permasalahan tentang kehidupan keluarga, karir, dan bisnis. 
Dengan para mentor yang berpengalaman di bidangnya menjadikan PersonalityTalk dipercaya menjadi media tempat belajar para Mahasiswa Psikologi, Praktisi SDM, Psikolog, Guru, Dosen, Praktisi NLP, Hypnoterapis, juga para Orang Tua yang ingin mendapatkan pembelajaran baik teori maupun praktik.
`;

export const layanan = [
  {
    id: 1,
    name: 'Konsultasi',
    slug: 'konsultasi',
    buttonname: 'Mulai Konsultasi',
    description: 'Dapatkan penyelesaian masalah kamu dengan ditangani oleh Psikolog dan Konsulen yang handal dan terpercaya, dengan berbagai topik yang ada.',
    icon_white: '/icons/konsultasi.png',
    icon_orange: '/icons/i-konsultasi.png',
    ialt: 'Icon Konsultasi',
    images: '/image/img-konsul.png',
    imagealt: 'Image Konsultasi',
  },
  {
    id: 2,
    name: 'Course',
    slug: 'course',
    buttonname: 'Mulai Course',
    description: 'Cara kamu untuk Memperkaya wawasan, Mengasah keterampilan, dan Mengasah kemampuan anda di bidang Psikologi ataupun SDM dengan materi yang cocok untuk Mahasiswa Psikologi.',
    icon_white: '/icons/course.png',
    icon_orange: '/icons/i-ecourse.png',
    ialt: 'Icon Course',
    images: '/image/img-course.png',
    imagealt: 'Image Course',
  },
  {
    id: 3,
    name: 'Tes Mental',
    slug: 'tes-mental',
    buttonname: 'Mulai Tes',
    description: 'Ketahui gambaran kesehatan mentalmu dan ketahui kebutuhan diri dengan mengisi asesmen tes dari PersonalityTalk secara gratis.',
    icon_white: '/icons/tes-mental.png',
    icon_orange: '/icons/i-test.png',
    ialt: 'Icon Tes Mental',
    images: '/image/img-test.png',
    imagealt: 'Image Tes Mental',
  },
  {
    id: 4,
    name: 'Informasi Penyakit',
    slug: 'informasi-penyakit-mental',
    buttonname: 'Cari Informasi',
    description: 'Cari segala informasi termasuk pengertian, gejala, dan dampak dari <b> Kesehatan Mental </b> yang dapat dimengerti dan cara penangannya',
    icon_white: '/icons/info-penyakit.png',
    icon_orange: '/icons/i-info.png',
    iconalt: 'Icon Penyakit Mental',
    images: '/image/img-info.png',
    imagealt: 'Image Penyakit Mental',
  },
]
export const penyakit = [
  { "id": 1, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan."},
  { "id": 2, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 3, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 4, "name": "Anxiety Disorder" , "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 5, "name": "Autism Spectrum Disorder (ASD)" , "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 6, "name": "Bipolar Disorder" , "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 7, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 8, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 9, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 10, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 11, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 12, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 13, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 14, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 15, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_4.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 16, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 17, "name": "Attention Deficit Hyperactivity Disorder (ADHD)", "author": "John Doe", "image": "/image/image_4.png", "description": "ADHD adalah gangguan neurodevelopmental yang ditandai dengan kurangnya perhatian, perilaku impulsif, dan hiperaktivitas." },
  { "id": 18, "name": "Major Depressive Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Major Depressive Disorder adalah gangguan mood yang menyebabkan perasaan sedih yang berkelanjutan dan hilangnya minat dalam aktivitas yang biasa dinikmati." },
  { "id": 19, "name": "Persistent Depressive Disorder (Dysthymia)", "author": "John Doe", "image": "/image/image_4.png", "description": "Persistent Depressive Disorder, juga dikenal sebagai dysthymia, adalah bentuk depresi kronis yang berkepanjangan tetapi dengan gejala yang kurang parah." },
  { "id": 20, "name": "Postpartum Depression", "author": "John Doe", "image": "/image/image_4.png", "description": "Postpartum Depression adalah depresi yang terjadi pada ibu setelah melahirkan, sering kali disertai dengan perasaan cemas, kelelahan, dan kesulitan merawat bayi." },
  { "id": 21, "name": "Premenstrual Dysphoric Disorder (PMDD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Premenstrual Dysphoric Disorder (PMDD) adalah bentuk parah dari sindrom pramenstruasi (PMS) yang menyebabkan perubahan suasana hati yang ekstrem, kelelahan, dan gejala fisik lainnya." },
  { "id": 22, "name": "Alzheimer's Disease", "author": "John Doe", "image": "/image/image_4.png", "description": "Alzheimer's Disease adalah gangguan neurodegeneratif yang menyebabkan penurunan fungsi kognitif dan memori, terutama pada orang lanjut usia." },
  { "id": 23, "name": "Paranoid Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Paranoid Personality Disorder adalah gangguan kepribadian di mana seseorang memiliki ketidakpercayaan yang mendalam terhadap orang lain dan mencurigai motif mereka." },
  { "id": 24, "name": "Schizoaffective Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Schizoaffective Disorder adalah kondisi mental yang melibatkan gejala skizofrenia serta gangguan mood seperti depresi atau mania." },
  { "id": 25, "name": "Histrionic Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Histrionic Personality Disorder adalah gangguan kepribadian di mana seseorang memiliki kebutuhan berlebihan untuk mendapatkan perhatian dan cenderung mencari drama." },
  { "id": 26, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 27, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 28, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 29, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 30, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 31, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_4.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 32, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 33, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 34, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 35, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 36, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 37, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 38, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 39, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 40, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 41, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 42, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 43, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 44, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 45, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 46, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 47, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_4.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 48, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 49, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 50, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 51, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 52, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 53, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 54, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 55, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 56, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 57, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 58, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 59, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 60, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 61, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 62, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 63, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_4.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 64, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 65, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 66, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 67, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 68, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 69, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 70, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 71, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 72, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 73, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 74, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 75, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 76, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 77, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 78, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_4.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 79, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_4.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 80, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_4.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 81, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_4.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 82, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_4.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 83, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 84, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 85, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 86, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 87, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 88, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 89, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 90, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 91, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 92, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 93, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 94, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 95, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_5.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 96, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 97, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_5.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 98, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 99, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 100, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 101, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 102, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 103, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 104, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 105, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 106, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 107, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 108, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 109, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 110, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 111, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_5.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 112, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 113, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_5.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 114, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 115, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 116, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 117, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 118, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 119, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 120, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 121, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 122, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 123, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 124, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 125, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 126, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 127, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_5.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 128, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 129, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_5.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 130, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 131, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 132, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 133, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Autism Spectrum Disorder (ASD) mempengaruhi kemampuan komunikasi, interaksi sosial, dan perilaku berulang pada individu." },
  { "id": 134, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Bipolar Disorder adalah gangguan mood yang menyebabkan perubahan suasana hati yang ekstrem dari mania ke depresi." },
  { "id": 135, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang memiliki obsesi berlebihan terhadap kekurangan fisik yang tidak signifikan." },
  { "id": 136, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan suasana hati yang tidak stabil dan hubungan yang tegang dengan orang lain." },
  { "id": 137, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Bulimia Nervosa adalah gangguan makan di mana seseorang terlibat dalam makan berlebihan diikuti dengan upaya untuk menghilangkan makanan melalui muntah atau penggunaan laksatif." },
  { "id": 138, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Dissociative Identity Disorder (DID) adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 139, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Generalized Anxiety Disorder adalah gangguan kecemasan yang ditandai dengan kekhawatiran berlebihan yang tidak terkendali." },
  { "id": 140, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Obsessive-Compulsive Disorder (OCD) adalah gangguan mental yang ditandai dengan obsesi dan dorongan untuk melakukan tindakan berulang (kompulsi)." },
  { "id": 141, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Panic Disorder adalah gangguan kecemasan di mana seseorang mengalami serangan panik yang tiba-tiba dan berulang kali." },
  { "id": 142, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_5.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan mental yang terjadi setelah seseorang mengalami atau menyaksikan kejadian traumatis." },
  { "id": 143, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_5.png", "description": "Schizophrenia adalah gangguan mental kronis yang mempengaruhi cara seseorang berpikir, merasakan, dan berperilaku, sering kali disertai dengan halusinasi atau delusi." },
  { "id": 144, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang membuat seseorang merasa takut atau cemas secara ekstrem dalam situasi sosial." },
  { "id": 145, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_5.png", "description": "Agoraphobia adalah jenis kecemasan yang membuat seseorang takut berada di tempat-tempat yang sulit atau tidak mungkin untuk melarikan diri atau mendapatkan bantuan." },
  { "id": 146, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_5.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan ketakutan berlebihan terhadap kenaikan berat badan dan distorsi citra tubuh." },
  { "id": 147, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif, eksploitasi, atau melanggar hak orang lain tanpa rasa bersalah." },
  { "id": 148, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_5.png", "description": "Anxiety Disorder adalah gangguan mental yang menyebabkan kecemasan berlebihan dan berkelanjutan." },
  { "id": 149, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_6.png", "description": "Autism Spectrum Disorder (ASD) adalah gangguan perkembangan yang mempengaruhi kemampuan komunikasi dan interaksi sosial." },
  { "id": 150, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Bipolar Disorder adalah gangguan mental yang ditandai dengan perubahan suasana hati yang ekstrem." },
  { "id": 151, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang terobsesi dengan kekurangan fisik yang tidak signifikan." },
  { "id": 152, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan ketidakstabilan emosi dan perilaku." },
  { "id": 153, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_6.png", "description": "Bulimia Nervosa adalah gangguan makan yang ditandai dengan siklus makan berlebihan diikuti dengan perilaku pembersihan." },
  { "id": 154, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Dissociative Identity Disorder adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 155, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Generalized Anxiety Disorder adalah gangguan yang ditandai dengan kekhawatiran berlebihan tentang berbagai hal." },
  { "id": 156, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Obsessive-Compulsive Disorder adalah gangguan yang ditandai dengan obsesi dan perilaku kompulsif." },
  { "id": 157, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Panic Disorder adalah gangguan kecemasan yang ditandai dengan serangan panik yang tiba-tiba." },
  { "id": 158, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_6.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan yang terjadi setelah mengalami atau menyaksikan peristiwa traumatis." },
  { "id": 159, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_6.png", "description": "Schizophrenia adalah gangguan mental serius yang mempengaruhi cara seseorang berpikir, merasakan, dan bertindak." },
  { "id": 160, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang menyebabkan ketakutan berlebihan dalam situasi sosial." },
  { "id": 161, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_6.png", "description": "Agoraphobia adalah ketakutan berlebihan terhadap situasi di mana melarikan diri mungkin sulit." },
  { "id": 162, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_6.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan penghindaran makanan dan penurunan berat badan ekstrem." },
  { "id": 163, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif dan pelanggaran hak orang lain." },
  { "id": 164, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Anxiety Disorder adalah gangguan yang ditandai dengan perasaan cemas dan ketegangan yang berlebihan." },
  { "id": 165, "name": "Autism Spectrum Disorder (ASD)", "author": "John Doe", "image": "/image/image_6.png", "description": "Autism Spectrum Disorder (ASD) adalah gangguan perkembangan yang mempengaruhi kemampuan komunikasi dan interaksi sosial." },
  { "id": 166, "name": "Bipolar Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Bipolar Disorder adalah gangguan mental yang ditandai dengan perubahan suasana hati yang ekstrem." },
  { "id": 167, "name": "Body Dysmorphic Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Body Dysmorphic Disorder adalah gangguan mental di mana seseorang terobsesi dengan kekurangan fisik yang tidak signifikan." },
  { "id": 168, "name": "Borderline Personality Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Borderline Personality Disorder adalah gangguan kepribadian yang ditandai dengan ketidakstabilan emosi dan perilaku." },
  { "id": 169, "name": "Bulimia Nervosa", "author": "John Doe", "image": "/image/image_6.png", "description": "Bulimia Nervosa adalah gangguan makan yang ditandai dengan siklus makan berlebihan diikuti dengan perilaku pembersihan." },
  { "id": 170, "name": "Dissociative Identity Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Dissociative Identity Disorder adalah gangguan mental di mana seseorang memiliki dua atau lebih identitas yang berbeda." },
  { "id": 171, "name": "Generalized Anxiety Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Generalized Anxiety Disorder adalah gangguan yang ditandai dengan kekhawatiran berlebihan tentang berbagai hal." },
  { "id": 172, "name": "Obsessive-Compulsive Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Obsessive-Compulsive Disorder adalah gangguan yang ditandai dengan obsesi dan perilaku kompulsif." },
  { "id": 173, "name": "Panic Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Panic Disorder adalah gangguan kecemasan yang ditandai dengan serangan panik yang tiba-tiba." },
  { "id": 174, "name": "Post-Traumatic Stress Disorder (PTSD)", "author": "John Doe", "image": "/image/image_6.png", "description": "Post-Traumatic Stress Disorder (PTSD) adalah gangguan yang terjadi setelah mengalami atau menyaksikan peristiwa traumatis." },
  { "id": 175, "name": "Schizophrenia", "author": "John Doe", "image": "/image/image_6.png", "description": "Schizophrenia adalah gangguan mental serius yang mempengaruhi cara seseorang berpikir, merasakan, dan bertindak." },
  { "id": 176, "name": "Social Anxiety Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Social Anxiety Disorder adalah gangguan kecemasan yang menyebabkan ketakutan berlebihan dalam situasi sosial." },
  { "id": 177, "name": "Agoraphobia", "author": "John Doe", "image": "/image/image_6.png", "description": "Agoraphobia adalah ketakutan berlebihan terhadap situasi di mana melarikan diri mungkin sulit." },
  { "id": 178, "name": "Anorexia Nervosa", "author": "John Doe", "image": "/image/image_6.png", "description": "Anorexia Nervosa adalah gangguan makan yang ditandai dengan penghindaran makanan dan penurunan berat badan ekstrem." },
  { "id": 179, "name": "Antisocial Personality Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Antisocial Personality Disorder ditandai dengan perilaku manipulatif dan pelanggaran hak orang lain." },
  { "id": 180, "name": "Anxiety Disorder", "author": "John Doe", "image": "/image/image_6.png", "description": "Anxiety Disorder adalah gangguan yang ditandai dengan perasaan cemas dan ketegangan yang berlebihan." },
]

export const alasan = [
  {
    id: 1,
    name: 'Privasi Terjamin',
    images: '/image/privasi.png',
    alt:'Image Privasi Terjamin',
  },
  {
    id: 2,
    name: 'Beragam Pilihan Topik',
    images: '/image/pilihan.png',
    alt:'Image Pilihan Topik',
  },
  {
    id: 3,
    name: 'Konsultasi Mudah & Realtime',
    images: '/image/topik.png',
    alt:'Image Topik Terupdate',
  },
  {
    id: 4,
    name: 'Layanan Lengkap',
    images: '/image/layanan.png',
    alt:'Image Terpercaya',
  }
]

export const artikel = [
  {
    id: 1,
    name: 'Artikel 1',
    images: '/image/artikel.png',
    alt:'Image Artikel 1',
    tanggal: '30 Desember 2024',
  },
  {
    id: 2,
    name: 'Artikel 2',
    images: '/image/artikel.png',
    alt:'Image Artikel 2',
    tanggal: '30 Desember 2024',
  },
  {
    id: 3,
    name: 'Artikel 3',
    images: '/image/artikel.png',
    alt:'Image Artikel 3',
    tanggal: '30 Desember 2024',
  },
  {
    id: 4,
    name: 'Artikel 4',
    images: '/image/artikel.png',
    alt:'Image Artikel 4',
    tanggal: '30 Desember 2024',
  },
]

export const TOPARTIKEL = artikel.slice(0, 3);