export const slides = [
  {
    imageSrc: '/image/Rectangle_6.png',
  },
  {
    imageSrc: '/image/Rectangle_6.png',
  },
  {
    imageSrc: '/image/Rectangle_6.png',
  }
];

export const description = `
PersonalityTalk adalah lembaga yang bergerak di bidang jasa training, coaching, dan consulting dalam bidang psikologi. Berdiri sejak tahun 2014, Alhamdulillah PersonalityTalk telah membantu banyak orang dalam menyelesaikan permasalahan tentang kehidupan keluarga, karir, dan bisnis. 
Dengan para mentor yang berpengalaman di bidangnya menjadikan PersonalityTalk dipercaya menjadi media tempat belajar para Mahasiswa Psikologi, Praktisi SDM, Psikolog, Guru, Dosen, Praktisi NLP, Hypnoterapis, juga para Orang Tua yang ingin mendapatkan pembelajaran baik teori maupun praktik.
`;

export const layanan = [
  {
    id: 1,
    name: 'Konsultasi',
    buttonname: 'Mulai Konsultasi',
    iconkeunggulan: '/image/group_7.png',
    description: 'Dapatkan penyelesaian masalah kamu dengan ditangani oleh Psikolog dan Konsulen yang handal dan terpercaya, dengan berbagai topik yang ada.',
    icons: '/icons/Icon.png',
    ialt: 'Icon Konsultasi',
    images: '/image/Group_3.png',
    imagealt: 'Image Konsultasi',
    slug: 'konsultasi',
  },
  {
    id: 2,
    name: 'Course',
    buttonname: 'Mulai Course',
    iconkeunggulan: '/image/group_7.png',
    description: 'Cara kamu untuk Memperkaya wawasan, Mengasah keterampilan, dan Mengasah kemampuan anda di bidang Psikologi ataupun SDM dengan materi yang cocok untuk Mahasiswa Psikologi.',
    icons: '/icons/Icon.png',
    ialt: 'Icon Course',
    images: '/image/Group_3.png',
    imagealt: 'Image Course',
    slug: 'course',
  },
  {
    id: 3,
    name: 'Tes Mental',
    buttonname: 'Mulai Tes',
    iconkeunggulan: '/image/group_7.png',
    description: 'Ketahui gambaran kesehatan mentalmu dan ketahui kebutuhan diri dengan mengisi asesmen tes dari PersonalityTalk secara gratis.',
    icons: '/icons/Icon.png',
    ialt: 'Icon Tes Mental',
    images: '/image/Group_3.png',
    imagealt: 'Image Tes Mental',
    slug: 'tes-mental',
  },
  {
    id: 4,
    name: 'Informasi Penyakit Mental',
    buttonname: 'Cari Informasi',
    iconkeunggulan: '/image/group_7.png',
    description: 'Cari segala informasi termasuk pengertian, gejala, dan dampak dari Penyakit Mental yang dapat dimengerti dan cara penangannya.',
    icons: '/icons/Icon.png',
    iconalt: 'Icon Penyakit Mental',
    images: '/image/Group_3.png',
    imagealt: 'Image Penyakit Mental',
    slug: 'informasi-penyakit-mental',
  },
]
export const penyakit = [
  { "id": 1, "name": "Agoraphobia" },
  { "id": 2, "name": "Anorexia Nervosa" },
  { "id": 3, "name": "Antisocial Personality Disorder" },
  { "id": 4, "name": "Anxiety Disorder" },
  { "id": 5, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 6, "name": "Bipolar Disorder" },
  { "id": 7, "name": "Body Dysmorphic Disorder" },
  { "id": 8, "name": "Borderline Personality Disorder" },
  { "id": 9, "name": "Bulimia Nervosa" },
  { "id": 10, "name": "Dissociative Identity Disorder" },
  { "id": 11, "name": "Generalized Anxiety Disorder" },
  { "id": 12, "name": "Obsessive-Compulsive Disorder" },
  { "id": 13, "name": "Panic Disorder" },
  { "id": 14, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 15, "name": "Schizophrenia" },
  { "id": 16, "name": "Social Anxiety Disorder" },
  { "id": 17, "name": "Agoraphobia" },
  { "id": 18, "name": "Anorexia Nervosa" },
  { "id": 19, "name": "Antisocial Personality Disorder" },
  { "id": 20, "name": "Anxiety Disorder" },
  { "id": 21, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 22, "name": "Bipolar Disorder" },
  { "id": 23, "name": "Body Dysmorphic Disorder" },
  { "id": 24, "name": "Borderline Personality Disorder" },
  { "id": 25, "name": "Bulimia Nervosa" },
  { "id": 26, "name": "Dissociative Identity Disorder" },
  { "id": 27, "name": "Generalized Anxiety Disorder" },
  { "id": 28, "name": "Obsessive-Compulsive Disorder" },
  { "id": 29, "name": "Panic Disorder" },
  { "id": 30, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 31, "name": "Schizophrenia" },
  { "id": 32, "name": "Social Anxiety Disorder" },
  { "id": 33, "name": "Agoraphobia" },
  { "id": 34, "name": "Anorexia Nervosa" },
  { "id": 35, "name": "Antisocial Personality Disorder" },
  { "id": 36, "name": "Anxiety Disorder" },
  { "id": 37, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 38, "name": "Bipolar Disorder" },
  { "id": 39, "name": "Body Dysmorphic Disorder" },
  { "id": 40, "name": "Borderline Personality Disorder" },
  { "id": 41, "name": "Bulimia Nervosa" },
  { "id": 42, "name": "Dissociative Identity Disorder" },
  { "id": 43, "name": "Generalized Anxiety Disorder" },
  { "id": 44, "name": "Obsessive-Compulsive Disorder" },
  { "id": 45, "name": "Panic Disorder" },
  { "id": 46, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 47, "name": "Schizophrenia" },
  { "id": 48, "name": "Social Anxiety Disorder" },
  { "id": 49, "name": "Agoraphobia" },
  { "id": 50, "name": "Anorexia Nervosa" },
  { "id": 51, "name": "Antisocial Personality Disorder" },
  { "id": 52, "name": "Anxiety Disorder" },
  { "id": 53, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 54, "name": "Bipolar Disorder" },
  { "id": 55, "name": "Body Dysmorphic Disorder" },
  { "id": 56, "name": "Borderline Personality Disorder" },
  { "id": 57, "name": "Bulimia Nervosa" },
  { "id": 58, "name": "Dissociative Identity Disorder" },
  { "id": 59, "name": "Generalized Anxiety Disorder" },
  { "id": 60, "name": "Obsessive-Compulsive Disorder" },
  { "id": 61, "name": "Panic Disorder" },
  { "id": 62, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 63, "name": "Schizophrenia" },
  { "id": 64, "name": "Social Anxiety Disorder" },
  { "id": 65, "name": "Agoraphobia" },
  { "id": 66, "name": "Anorexia Nervosa" },
  { "id": 67, "name": "Antisocial Personality Disorder" },
  { "id": 68, "name": "Anxiety Disorder" },
  { "id": 69, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 70, "name": "Bipolar Disorder" },
  { "id": 71, "name": "Body Dysmorphic Disorder" },
  { "id": 72, "name": "Borderline Personality Disorder" },
  { "id": 73, "name": "Bulimia Nervosa" },
  { "id": 74, "name": "Dissociative Identity Disorder" },
  { "id": 75, "name": "Generalized Anxiety Disorder" },
  { "id": 76, "name": "Obsessive-Compulsive Disorder" },
  { "id": 77, "name": "Panic Disorder" },
  { "id": 78, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 79, "name": "Schizophrenia" },
  { "id": 80, "name": "Social Anxiety Disorder" },
  { "id": 81, "name": "Agoraphobia" },
  { "id": 82, "name": "Anorexia Nervosa" },
  { "id": 83, "name": "Antisocial Personality Disorder" },
  { "id": 84, "name": "Anxiety Disorder" },
  { "id": 85, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 86, "name": "Bipolar Disorder" },
  { "id": 87, "name": "Body Dysmorphic Disorder" },
  { "id": 88, "name": "Borderline Personality Disorder" },
  { "id": 89, "name": "Bulimia Nervosa" },
  { "id": 90, "name": "Dissociative Identity Disorder" },
  { "id": 91, "name": "Generalized Anxiety Disorder" },
  { "id": 92, "name": "Obsessive-Compulsive Disorder" },
  { "id": 93, "name": "Panic Disorder" },
  { "id": 94, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 95, "name": "Schizophrenia" },
  { "id": 96, "name": "Social Anxiety Disorder" },
  { "id": 97, "name": "Agoraphobia" },
  { "id": 98, "name": "Anorexia Nervosa" },
  { "id": 99, "name": "Antisocial Personality Disorder" },
  { "id": 100, "name": "Anxiety Disorder" },
  { "id": 101, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 102, "name": "Bipolar Disorder" },
  { "id": 103, "name": "Body Dysmorphic Disorder" },
  { "id": 104, "name": "Borderline Personality Disorder" },
  { "id": 105, "name": "Bulimia Nervosa" },
  { "id": 106, "name": "Dissociative Identity Disorder" },
  { "id": 107, "name": "Generalized Anxiety Disorder" },
  { "id": 108, "name": "Obsessive-Compulsive Disorder" },
  { "id": 109, "name": "Panic Disorder" },
  { "id": 110, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 111, "name": "Schizophrenia" },
  { "id": 112, "name": "Social Anxiety Disorder" },
  { "id": 113, "name": "Agoraphobia" },
  { "id": 114, "name": "Anorexia Nervosa" },
  { "id": 115, "name": "Antisocial Personality Disorder" },
  { "id": 116, "name": "Anxiety Disorder" },
  { "id": 117, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 118, "name": "Bipolar Disorder" },
  { "id": 119, "name": "Body Dysmorphic Disorder" },
  { "id": 120, "name": "Borderline Personality Disorder" },
  { "id": 121, "name": "Bulimia Nervosa" },
  { "id": 122, "name": "Dissociative Identity Disorder" },
  { "id": 123, "name": "Generalized Anxiety Disorder" },
  { "id": 124, "name": "Obsessive-Compulsive Disorder" },
  { "id": 125, "name": "Panic Disorder" },
  { "id": 126, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 127, "name": "Schizophrenia" },
  { "id": 128, "name": "Social Anxiety Disorder" },
  { "id": 129, "name": "Agoraphobia" },
  { "id": 130, "name": "Anorexia Nervosa" },
  { "id": 131, "name": "Antisocial Personality Disorder" },
  { "id": 132, "name": "Anxiety Disorder" },
  { "id": 133, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 134, "name": "Bipolar Disorder" },
  { "id": 135, "name": "Body Dysmorphic Disorder" },
  { "id": 136, "name": "Borderline Personality Disorder" },
  { "id": 137, "name": "Bulimia Nervosa" },
  { "id": 138, "name": "Dissociative Identity Disorder" },
  { "id": 139, "name": "Generalized Anxiety Disorder" },
  { "id": 140, "name": "Obsessive-Compulsive Disorder" },
  { "id": 141, "name": "Panic Disorder" },
  { "id": 142, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 143, "name": "Schizophrenia" },
  { "id": 144, "name": "Social Anxiety Disorder" },
  { "id": 145, "name": "Agoraphobia" },
  { "id": 146, "name": "Anorexia Nervosa" },
  { "id": 147, "name": "Antisocial Personality Disorder" },
  { "id": 148, "name": "Anxiety Disorder" },
  { "id": 149, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 150, "name": "Bipolar Disorder" },
  { "id": 151, "name": "Body Dysmorphic Disorder" },
  { "id": 152, "name": "Borderline Personality Disorder" },
  { "id": 153, "name": "Bulimia Nervosa" },
  { "id": 154, "name": "Dissociative Identity Disorder" },
  { "id": 155, "name": "Generalized Anxiety Disorder" },
  { "id": 156, "name": "Obsessive-Compulsive Disorder" },
  { "id": 157, "name": "Panic Disorder" },
  { "id": 158, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 159, "name": "Schizophrenia" },
  { "id": 160, "name": "Social Anxiety Disorder" },
  { "id": 161, "name": "Agoraphobia" },
  { "id": 162, "name": "Anorexia Nervosa" },
  { "id": 163, "name": "Antisocial Personality Disorder" },
  { "id": 164, "name": "Anxiety Disorder" },
  { "id": 165, "name": "Autism Spectrum Disorder (ASD)" },
  { "id": 166, "name": "Bipolar Disorder" },
  { "id": 167, "name": "Body Dysmorphic Disorder" },
  { "id": 168, "name": "Borderline Personality Disorder" },
  { "id": 169, "name": "Bulimia Nervosa" },
  { "id": 170, "name": "Dissociative Identity Disorder" },
  { "id": 171, "name": "Generalized Anxiety Disorder" },
  { "id": 172, "name": "Obsessive-Compulsive Disorder" },
  { "id": 173, "name": "Panic Disorder" },
  { "id": 174, "name": "Post-Traumatic Stress Disorder (PTSD)" },
  { "id": 175, "name": "Schizophrenia" },
  { "id": 176, "name": "Social Anxiety Disorder" },
  { "id": 177, "name": "Agoraphobia" },
  { "id": 178, "name": "Anorexia Nervosa" },
  { "id": 179, "name": "Antisocial Personality Disorder" },
  { "id": 180, "name": "Anxiety Disorder" },
]